apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wumine2/argocd-demo.git #This is the url of the repo we want argocd to monitor
    targetRevision: HEAD
    path: prod #inside the git repo, this is where the yaml file can be located.
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true #argocd will recreate a deleted pod to ensure that the desired state is maintained.
      prune: true #if a pod is added in the cluster and there is no manifest for it in the repository, argocd will delete the pod. The repository is the only source of truth
