apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/wumine2/argocd-test.git #This is the repository argocd is trying to connect to
  password: #The access token to github
  username: #github username
